import './globals.css'
import { Plus_Jakarta_Sans} from 'next/font/google'
import Menu from './components/menu'




export const metadata = {
  title: 'UX Albadam',
  description: 'Generated by create next app',
}

const Jakarta= Plus_Jakarta_Sans({
  weights: [400,500,600, 700],
  styles: ['normal', 'italic'],
  subsets: ['latin-ext'],

})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={Jakarta.className}>
        <Menu />
      
        {children}
      



      
     
      </body>
      
    </html>
  )
}
